#SENTENCIAS WHILE-ELSE
#Ejrmplo 1
#Pide al usuario un numero y lo conierte a entero.
# numero=int(input("Ingresar numero de la tabla de multiplicar "))

# #Inicia el contador 1 (Primer multiplicador)
# i=1

# print(F"\Inicia el contador en 1 {numero}: ")

# while i <=10:
#     print(f"{numero} * {i} = {numero * i}")
#     i += 1 #Actualizacion

#Ejemplo 2
# numero = 1
# while True:
#     numero += 1
#     print(numero)
#     break

#Ejemplo 3
# x = 10 
# while True:
#     x -= 1
#     print(x)
#     if x == 0:
#         break
#     print("Fin del bucle")

# #Ejercicio 4
# chance = 1
# while chance <=3:
#     txt =input("Escribe si: ")
#     if txt == "si": 
#         print("Ok, lo conseguiste en el intento", chance)
#         break
#     chance += 1
# else:
#     print("Has gastado tus tres intentos")


   
